from Cylinder import Cylinder
x = Cylinder("a")
x.setRadius(1)
x.setColor("Red")
x.setheight(1)
print("the current radius is", x.getRadius())
print("the current color is", x.getColor())
print("the current height is", x.getheight())
Radius = int(input("Enter New Radius: "))
while Radius <= 0:
    print("Radius cannot be equal to or less than 0")
    Radius = float(input("Please, Re-enter Radius:"))
x.setRadius(Radius)
print("the new Radius is:", x.getRadius())
x.setColor(input("Enter New Color: "))
print("The new Color is:", x.getColor())
x.setheight(float(input("Enter New Height: ")))
print("The new height is:", x.getheight())
print("and the volume is:", x.getvolume())
print(x.__str__())